using Microsoft.EntityFrameworkCore;

namespace MvcApplication.DAL.Models
{
    [Keyless]
    public partial class Hospital
    {
        public int auto_id { get; set; }
        public string? name { get; set; }
        public string? address { get; set; }
        public string? county { get; set; }
        public string? sub_county { get; set; }
        public string? region { get; set; }
        public string? town { get; set; }
        public string? HospitalCatagry { get; set; }
        public string? city { get; set; }
        public string? pin { get; set; }
        public string? state { get; set; }
        public string? contact { get; set; }
        public string? phone1 { get; set; }
        public string? phone3 { get; set; }
        public string? phone4 { get; set; }
        public string? regd_no { get; set; }
        public string? nob { get; set; }
        public string? userid { get; set; }
        public decimal? Disc { get; set; }
        public DateTime? dated { get; set; }
        public string? remarks { get; set; }
        public string? Email { get; set; }
        public string? Email2 { get; set; }
        public string? Email3 { get; set; }
        public int BlackList { get; set; }
        public DateTime? BlackDate { get; set; }
        public string? Reason { get; set; }
        public string? AuthBy { get; set; }
        public string? BUser { get; set; }
        public DateTime? EntryDate { get; set; }
        public DateTime? Wdate { get; set; }
        public string? WReason { get; set; }
        public string? WAuthBy { get; set; }
        public string? WUser { get; set; }
        public DateTime? WEntryDate { get; set; }
        public string? ExmBy { get; set; }
        public DateTime? ExmAppFrom { get; set; }
        public string? ExmReason { get; set; }
        public int ExmSts { get; set; }
        public string? TDSRate { get; set; }
        public string? PanNo { get; set; }
        public string? ServiceTaxNo { get; set; }
        public string? TIN { get; set; }
        public string? AccountName { get; set; }
        public string? AccountType { get; set; }
        public string? AccountNo { get; set; }
        public string? BankName { get; set; }
        public string? Branch { get; set; }
        public string? RTGSCode { get; set; }
        public string? MICRCode { get; set; }
        public int Networkable { get; set; }
        public DateTime? Ndate { get; set; }
        public int Taxable { get; set; }
        public DateTime? Tdate { get; set; }
        public string? BankCity { get; set; }
        public string? ProviderType { get; set; }
        public string? CareLavel { get; set; }
        public DateTime? RegdExpDate { get; set; }
        public DateTime? MOUExpDate { get; set; }
        public decimal? STDCode { get; set; }
        public string? HospArea { get; set; }
        public string? HospGrade { get; set; }
        public decimal? annualcap { get; set; }
        public string? InsuHospCode { get; set; }
        public string? latitude { get; set; }
        public string? longitude { get; set; }
        public string? IIBCode { get; set; }
        public string? ROHINIID { get; set; }
        public string? CashlessStatus { get; set; }
        public string? ppnhospital { get; set; }
        public string? PPnId { get; set; }
        public string? TPAEmail { get; set; }
        public string? FinanceDeptEmail { get; set; }
        public string? MarketingDeptEmail { get; set; }
        public string? HospitalOwner_DirectorEmail { get; set; }
        public string? FinanceContactName { get; set; }
        public string? Finance_Mobile { get; set; }
        public string? Finance_LandLine { get; set; }
        public string? MarketingContactName { get; set; }
        public string? Marketing_Mobile { get; set; }
        public string? Marketing_LandLine { get; set; }
        public string? DirectorContactName { get; set; }
        public string? Director_Mobile { get; set; }
        public string? Director_LandLine { get; set; }
        public string? TierType { get; set; }
        public DateTime? i_date { get; set; }
        public string? Modified_By { get; set; }
        public DateTime? Modified_At { get; set; }
        public string? PreAccreditationNo { get; set; }
        public string? NABHProgressiveCertificationNo { get; set; }
        public string? NABHAccreditationNo { get; set; }
        public string? JCIAccreditationNo { get; set; }
        public string? ISOCertification { get; set; }
        public string? NABHApplication { get; set; }
        public string? Zone { get; set; }
        public string? CityType { get; set; }
        public DateTime? MOURenewalDate { get; set; }
        public DateTime? MOURenewalExpiryDate { get; set; }
        public string? EntryPurpose { get; set; }
        public string? SpecialCorpName { get; set; }
        public DateTime? WatchListDate { get; set; }
        public string? WatchListReason { get; set; }
        public string? WatchListAuthBy { get; set; }
        public string? WatchListUser { get; set; }
        public DateTime? WatchListEntryDate { get; set; }
        public int WatchList { get; set; }
        public DateTime? RohiniStartDate { get; set; }
        public DateTime? RohiniExpDate { get; set; }
        public DateTime? NABHStartDate { get; set; }
        public DateTime? NABHExpDate { get; set; }
        public string? MegaPolicyHospital { get; set; }
        public decimal? NumberOfDoctor { get; set; }
        public decimal? NoOfDoctorsApprovedByMCI { get; set; }
        public decimal? No_Of_Cnsltnt { get; set; }
        public decimal? No_of_sergeon { get; set; }
        public decimal? TotalNo_Nurse { get; set; }
        public decimal? TotlNO_IcBeds { get; set; }
        public decimal? NoDoctr_MBbs_Md { get; set; }
        public string? NoOfShiftWiseNurse { get; set; }
        public string? DoctrBedRatio { get; set; }
        public string? NurseBedRatio { get; set; }
        public string? DctrBedratio_Icu { get; set; }
        public string? NurseBedratio_Icu { get; set; }
        public DateTime? AvgAdmisnTime { get; set; }
        public DateTime? AvgDischargeTime { get; set; }
        public decimal? AvgLengthStay_Mediclcase { get; set; }
        public decimal? AvgLengthStay_SurgiclCse { get; set; }
        public string? C_sectnRate { get; set; }
        public string? HosptalWebAdrss { get; set; }
        public decimal? No_Of_qualified_Nurse_For_ICU { get; set; }
        public decimal? No_of_Doctor_MBBSMD_For_ICU { get; set; }
        public decimal? NoOfFullTimeStaff { get; set; }
        public string? NearestOfficeBranch { get; set; }
        public string? Refferal { get; set; }
        public string? FacilityStatus { get; set; }
        public string? InpatientStatus { get; set; }
        public string? Status { get; set; }
        public DateTime? IDATE { get; set; }
        public string? Description { get; set; }
        public string? Stakholder { get; set; }
        public string? ProviderStatus { get; set; }
        public decimal? CapitationAmount { get; set; }
        public string? CoPay { get; set; }
        public decimal? CoPayAmount { get; set; }
        public int SchemeId { get; set; }

    }
}
